In [1]:
# creating arrays of ones, but with differing dtypes
import numpy as np
int_ones = np.ones((2,2),dtype = np.int8)
int_ones

array([[1, 1],
       [1, 1]], dtype=int8)

In [2]:
#creating an array filled with unsigned integers:
uint_ones = np.ones((2,2),dtype = np.uint8)
uint_ones

array([[1, 1],
       [1, 1]], dtype=uint8)

In [3]:
#creating array filled with strings
string_arr = np.array(["sam","Bill","Gery"])
string_arr

array(['sam', 'Bill', 'Gery'], dtype='<U4')

In [4]:
#always specify your data type explicitely
string_arr[1]="Waldo"
string_arr

array(['sam', 'Wald', 'Gery'], dtype='<U4')

## Special Numeric Values

nan:->Not a number.
inf:->indicates a quantity that is arbitrarily large.
-inf :-> indicates a quantity that is arbitrarily small.
(==) sign does not work for nan, but work for inf.

In [5]:
#write a program to create an array filled with 1,-1 and 0, and then divide it by zero. 

vec1 = np.array([1,-1,0],dtype=np.float16)
vec2= vec1/0
vec2

array([ inf, -inf,  nan], dtype=float16)

In [6]:
#How can we detect special values?
for i in vec2:
    print(i)
    print('-----')
    print('inf: '+str(i==np.inf))
    print('-inf: '+str(i==-np.inf))
    print('NaN: ' +str(i==np.nan)) #Dosent work!
    print('\n\n')

inf
-----
inf: True
-inf: False
NaN: False



-inf
-----
inf: False
-inf: True
NaN: False



nan
-----
inf: False
-inf: False
NaN: False





In [7]:
#Abetter way 
for i in vec2:
    print(i)
    print('------')
    print('inf: '+str(i==np.inf))
    print("-inf: "+str(i==-np.inf))
    print('Nan: '+str(np.isnan(i)))  #does work!
    print("\n\n")

inf
------
inf: True
-inf: False
Nan: False



-inf
------
inf: False
-inf: True
Nan: False



nan
------
inf: False
-inf: False
Nan: True





In [8]:
#write a numpy program to detect finite versus infinite:

for i in vec2:
    print(i)
    print('------')
    print('is finite: '+ str(np.isfinite(i)))
    print('is infinite: '+ str(np.isinf(i)))
    print('\n\n')

inf
------
is finite: False
is infinite: True



-inf
------
is finite: False
is infinite: True



nan
------
is finite: False
is infinite: False





In [9]:
vec3 = np.array([999],dtype=np.float64)
vec3

array([999.])

In [10]:
vec3[0]**vec3[0]

inf

In [11]:
vec4 = np.ones(5)
vec4[0]=np.nan
vec4

array([nan,  1.,  1.,  1.,  1.])

In [12]:
np.sum(vec4)

nan

In [13]:
np.nansum(vec4)

4.0

# Creating Numpy array

## Creating ndarray

In [14]:
import numpy as np 

vec1 = np.ones((5))

print(vec1)

[1. 1. 1. 1. 1.]


In [15]:
vec1.dtype

dtype('float64')

In [16]:
#the wrong way
vec1.dtype=np.int8
print(vec1)
vec1.dtype

[  0   0   0   0   0   0 -16  63   0   0   0   0   0   0 -16  63   0   0
   0   0   0   0 -16  63   0   0   0   0   0   0 -16  63   0   0   0   0
   0   0 -16  63]


dtype('int8')

In [17]:
#The correct way
vec1 = np.ones((5))
vec1 = np.array(vec1, dtype=np.int8)
print(vec1)

[1 1 1 1 1]


In [18]:
print(vec1.dtype)

int8


In [19]:
vec1

array([1, 1, 1, 1, 1], dtype=int8)

In [20]:
#three dimensional array
arr1 = np.zeros((2,2,2),dtype=np.float64)
arr1

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [21]:
#write a numpy program to create a matrix filled with random data
mat1 = np.random.randn(3,3)
mat1

array([[-0.26939652, -0.88834443, -0.20841095],
       [ 2.08533131, -1.38516129, -1.56280387],
       [-0.32849429,  1.73964854,  0.51429364]])

In [22]:
mat2 = np.array([["boo",'jane'],["bill","janet"]])
print(mat2)

[['boo' 'jane']
 ['bill' 'janet']]


In [23]:
mat2.dtype

dtype('<U5')

In [24]:
#using tuple to create an array
arr2 = np.array([[(1,3,5),(2,4,5)],[(1,np.nan,1),(2,2,2)]])
print(arr2)

[[[ 1.  3.  5.]
  [ 2.  4.  5.]]

 [[ 1. nan  1.]
  [ 2.  2.  2.]]]


In [25]:
#to get independent copy of any array use copy()

mat2_cpy = mat2.copy()
mat2[0,0]="amy"
print(mat2)

[['amy' 'jane']
 ['bill' 'janet']]


In [26]:
%pwd

'/home/jagdish/pytn/data science/numpy'

In [27]:
#to change directory
#%cd D

In [28]:
#create an npy file, which is a native file format for NumPy.
#this is binary file now in our working directory
np.save("arr1",arr1)

In [29]:
#we can load the array in this file using load()
arr1_new = np.load("arr1.npy")
print(arr1_new)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [30]:
#create a csv file
np.savetxt("mat1.csv",mat1, delimiter=",")

In [31]:
#opening the file
mat1file = open("mat1.csv","r")
for l in mat1file:
    print(l)

-2.693965176108644166e-01,-8.883444258713735220e-01,-2.084109522025208716e-01

2.085331314570667782e+00,-1.385161293781712377e+00,-1.562803865277407667e+00

-3.284942933394364717e-01,1.739648535644215510e+00,5.142936374521165366e-01



In [32]:
#closing the file
mat1file.close()

##Loading Method

**arr=load(file)**:- Load file(either a.npy or .npzfile) and store ndarray in arr


**arr=loadtxt(file,dtype,delimiter)**:- Load ndarray in file, a text file, and save to arr, optional argument delimiter gives string or character seprating columns(so use delimiter=',' for csv file), and dtype specifies dtype(if structured, the array will be one-dimenshional, with row per datum and number of columns matching number of fields in data type)

**arr=fromfile(file,count,sep)**:- arr is loaded from file(either an open file object or a filename), with array items seprated by sep; if sep="",this will be a binary file(text otherwise); count determines number of items read(count=-1 for all)

In [33]:
#load the contents of the file that I have just created
mat1_new = np.loadtxt("mat1.csv",delimiter = ",")
print(mat1_new)

[[-0.26939652 -0.88834443 -0.20841095]
 [ 2.08533131 -1.38516129 -1.56280387]
 [-0.32849429  1.73964854  0.51429364]]


# Operations on NumPy arrays

## access and manipulate subsets of array data.

* Slicing

* Arithmetic

* Linear algebra

* array method and functions.

In [34]:
## Slicing array with colons

import numpy as np 

#creating 3 dimenshional array

arr1 =np.array([[["joey","bob","srah"],
["Margaret","Rachel","Jim"],
["Wayne","Joey","Liam"]],

[["Max","Maxine","Richard"],
["Harold","Curtis","Simon"],
["Bob","Liam","Simon"]],

[["Wayne","Sarah","Lucy"],
["Lucy","Kurtis","Yu"],
["Joye","Lex","Alex"]]])

print(arr1)

[[['joey' 'bob' 'srah']
  ['Margaret' 'Rachel' 'Jim']
  ['Wayne' 'Joey' 'Liam']]

 [['Max' 'Maxine' 'Richard']
  ['Harold' 'Curtis' 'Simon']
  ['Bob' 'Liam' 'Simon']]

 [['Wayne' 'Sarah' 'Lucy']
  ['Lucy' 'Kurtis' 'Yu']
  ['Joye' 'Lex' 'Alex']]]


In [35]:
arr2 = arr1[:, :,0].copy()
print(arr2)

[['joey' 'Margaret' 'Wayne']
 ['Max' 'Harold' 'Bob']
 ['Wayne' 'Lucy' 'Joye']]


In [36]:
#changing new array
arr2[1,1]="Attila"
print(arr2)

[['joey' 'Margaret' 'Wayne']
 ['Max' 'Attila' 'Bob']
 ['Wayne' 'Lucy' 'Joye']]


In [37]:
#no change in original 
arr1

array([[['joey', 'bob', 'srah'],
        ['Margaret', 'Rachel', 'Jim'],
        ['Wayne', 'Joey', 'Liam']],

       [['Max', 'Maxine', 'Richard'],
        ['Harold', 'Curtis', 'Simon'],
        ['Bob', 'Liam', 'Simon']],

       [['Wayne', 'Sarah', 'Lucy'],
        ['Lucy', 'Kurtis', 'Yu'],
        ['Joye', 'Lex', 'Alex']]], dtype='<U8')

In [38]:
#choosing manually the "cross" elements
print(arr2[[1,1,1,0,2],[0,1,2,1,1]])

['Max' 'Attila' 'Bob' 'Margaret' 'Lucy']


In [39]:
#upper-left corner
print(arr2[:2,:2])

[['joey' 'Margaret']
 ['Max' 'Attila']]


In [40]:
#selecting array from middle column
print(arr2[:,1])

['Margaret' 'Attila' 'Lucy']


In [41]:
#select element from the middle column but we will not flatten the matrix and we'll keep its shape:

print(arr2[:,[1]])

[['Margaret']
 ['Attila']
 ['Lucy']]


In [42]:
#last two rows of middle column
print(arr2[1:,1])

['Attila' 'Lucy']


In [43]:
#Reverse the row order
print(arr2[::-1,:])

[['Wayne' 'Lucy' 'Joye']
 ['Max' 'Attila' 'Bob']
 ['joey' 'Margaret' 'Wayne']]


In [44]:
#selecting odd-number colums
print(arr2[:,0:3:2])

[['joey' 'Wayne']
 ['Max' 'Bob']
 ['Wayne' 'Joye']]


In [45]:
#choose a 2x2x2 corner cube:
print(arr1[0:2, 0:2, 0:2])

[[['joey' 'bob']
  ['Margaret' 'Rachel']]

 [['Max' 'Maxine']
  ['Harold' 'Curtis']]]


In [46]:
#selecting the middle slice, but keep an extra dimension
print(arr1[:,1, np.newaxis, :])

[[['Margaret' 'Rachel' 'Jim']]

 [['Harold' 'Curtis' 'Simon']]

 [['Lucy' 'Kurtis' 'Yu']]]


## Advance Indexing

In [47]:
#Select The element of arr2 that are not wayne
print(arr2[arr2 !="wayne"])

['joey' 'Margaret' 'Wayne' 'Max' 'Attila' 'Bob' 'Wayne' 'Lucy' 'Joye']


In [48]:
#A peak of the indexing boolean array
print(arr2 !="wayne")

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [49]:
#Select, effectively, an array holding the data in the corners
idx0 = np.array([[0,0],[2,-2]])

idx1 = np.array([[0,2],[0,2]])

print(arr2[idx0, idx1])

[['joey' 'Wayne']
 ['Wayne' 'Bob']]


In [50]:
#All entries that are not Curtis
print(arr1[arr1 !="Curtis"])

['joey' 'bob' 'srah' 'Margaret' 'Rachel' 'Jim' 'Wayne' 'Joey' 'Liam' 'Max'
 'Maxine' 'Richard' 'Harold' 'Simon' 'Bob' 'Liam' 'Simon' 'Wayne' 'Sarah'
 'Lucy' 'Lucy' 'Kurtis' 'Yu' 'Joye' 'Lex' 'Alex']


In [51]:
#A peak at the indexing array
print(arr1 !="Curtis")

[[[ True  True  True]
  [ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True False  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]
  [ True  True  True]]]


In [52]:
# Get a 2x2x2 matrix with corner element
#Row indices
idx = np.array([[[0,0],[0,0]],[[2,2],[2,2]]])

#Column indices
idx1 = np.array([[[0,2],[0,2]],[[0,2],[0,2]]])

#depth indices
idx2 = np.array([[[0,0],[2,2]],[[0,0],[2,2]]])

print(arr1[idx0,idx1,idx2])

[[['joey' 'Wayne']
  ['Lucy' 'Simon']]

 [['joey' 'Wayne']
  ['Lucy' 'Simon']]]


## Expanding arrays

In [53]:
#The concatenate function allows binding arrays together along a common axis

#add a new row
arr2 = np.concatenate((arr2, np.array([["sam","Joe","Bill"]])),axis=0)
print(arr2)

[['joey' 'Margaret' 'Wayne']
 ['Max' 'Attila' 'Bob']
 ['Wayne' 'Lucy' 'Joye']
 ['sam' 'Joe' 'Bill']]


In [54]:
#Add a new column
arr2 = np.concatenate((arr2, np.array([["Maya"],["Nana"],["Gus"],["Greg"]])),axis=1)
print(arr2)

[['joey' 'Margaret' 'Wayne' 'Maya']
 ['Max' 'Attila' 'Bob' 'Nana']
 ['Wayne' 'Lucy' 'Joye' 'Gus']
 ['sam' 'Joe' 'Bill' 'Greg']]


## Arithematic and linear algebra with arrays

In [55]:
import numpy as np 
from numpy.random import randn
import numpy.linalg as ln 

arr1 = np.array(randn(3,3,3)*10, dtype = np.int64)
arr2 = np.array(randn(3,3,3)*10, dtype = np.int64)
print(arr1)

[[[  0  -4   9]
  [ -2   6  14]
  [ 11   6  -3]]

 [[  3 -10   3]
  [-10  -3  11]
  [ 18   0  -2]]

 [[  1   3  -2]
  [  6  -3  15]
  [ -6   5   4]]]


In [56]:
print(arr2)

[[[ -5   2   2]
  [ -7  12   0]
  [ 16  -3  -6]]

 [[ -3 -13   8]
  [ 20 -21  -5]
  [ 12  -9  -4]]

 [[-10  -3  -1]
  [ 13  17  22]
  [-15   7   6]]]


In [57]:
#it can involve arrays and scalars
print(arr1+100)

[[[100  96 109]
  [ 98 106 114]
  [111 106  97]]

 [[103  90 103]
  [ 90  97 111]
  [118 100  98]]

 [[101 103  98]
  [106  97 115]
  [ 94 105 104]]]


In [58]:
#divide element in arr1 by 2
print(arr1/2)

[[[ 0.  -2.   4.5]
  [-1.   3.   7. ]
  [ 5.5  3.  -1.5]]

 [[ 1.5 -5.   1.5]
  [-5.  -1.5  5.5]
  [ 9.   0.  -1. ]]

 [[ 0.5  1.5 -1. ]
  [ 3.  -1.5  7.5]
  [-3.   2.5  2. ]]]


In [59]:
#raise every element in arr1 to the power of 2
print(arr1**2)

[[[  0  16  81]
  [  4  36 196]
  [121  36   9]]

 [[  9 100   9]
  [100   9 121]
  [324   0   4]]

 [[  1   9   4]
  [ 36   9 225]
  [ 36  25  16]]]


In [60]:
#multiply content of arr1 and arr2

print(arr1 * arr2)

[[[   0   -8   18]
  [  14   72    0]
  [ 176  -18   18]]

 [[  -9  130   24]
  [-200   63  -55]
  [ 216    0    8]]

 [[ -10   -9    2]
  [  78  -51  330]
  [  90   35   24]]]


In [61]:
print(arr1**(arr2/4))

[[[            inf             nan  3.00000000e+00]
  [            nan  2.16000000e+02  1.00000000e+00]
  [ 1.46410000e+04  2.60847430e-01             nan]]

 [[ 4.38691338e-01             nan  9.00000000e+00]
  [-1.00000000e+05             nan  4.99182261e-02]
  [ 5.83200000e+03             inf -5.00000000e-01]]

 [[ 1.00000000e+00  4.38691338e-01             nan]
  [ 3.38058269e+02             nan  2.94104673e+06]
  [            nan  1.67185076e+01  8.00000000e+00]]]


## Broadcasting

In [67]:
arr3 = np.array(randn(1,1,3))

In [68]:
print(arr3.shape)

(1, 1, 3)


In [69]:
print(arr1*arr3)

[[[ 0.          4.85214862 -5.76796357]
  [-1.29698518 -7.27822293 -8.97238777]
  [ 7.13341848 -7.27822293  1.92265452]]

 [[ 1.94547777 12.13037155 -1.92265452]
  [-6.48492589  3.63911146 -7.04973325]
  [11.67286661 -0.          1.28176968]]

 [[ 0.64849259 -3.63911146  1.28176968]
  [ 3.89095554  3.63911146 -9.61327261]
  [-3.89095554 -6.06518577 -2.56353936]]]


In [70]:
arr4 = arr3.transpose((0,2,1))
print(arr4)

[[[ 0.64849259]
  [-1.21303715]
  [-0.64088484]]]


In [71]:
print(arr1*arr4)

[[[  0.          -2.59397036   5.83643331]
  [  2.42607431  -7.27822293 -16.98252017]
  [ -7.04973325  -3.84530904   1.92265452]]

 [[  1.94547777  -6.48492589   1.94547777]
  [ 12.13037155   3.63911146 -13.3434087 ]
  [-11.53592713  -0.           1.28176968]]

 [[  0.64849259   1.94547777  -1.29698518]
  [ -7.27822293   3.63911146 -18.19555732]
  [  3.84530904  -3.2044242   -2.56353936]]]


In [72]:
arr5 = arr3.transpose((2,0,1))
print(arr5)

[[[ 0.64849259]]

 [[-1.21303715]]

 [[-0.64088484]]]


In [73]:
print(arr1*arr5)

[[[  0.          -2.59397036   5.83643331]
  [ -1.29698518   3.89095554   9.07889625]
  [  7.13341848   3.89095554  -1.94547777]]

 [[ -3.63911146  12.13037155  -3.63911146]
  [ 12.13037155   3.63911146 -13.3434087 ]
  [-21.83466879  -0.           2.42607431]]

 [[ -0.64088484  -1.92265452   1.28176968]
  [ -3.84530904   1.92265452  -9.61327261]
  [  3.84530904  -3.2044242   -2.56353936]]]


# Linear algebra

In [74]:
arr4 = arr3.transpose((0,2,1))
print(arr4)

[[[ 0.64849259]
  [-1.21303715]
  [-0.64088484]]]


In [75]:
arr6 = np.arange(0,8)
print(arr6)

[0 1 2 3 4 5 6 7]


In [76]:
print(arr6.reshape(2,2,2))

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [77]:
from sklearn.datasets import load_iris

#load iris data set

iris = load_iris().data[:, :]
print(iris)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [78]:
print(iris.T)

[[5.1 4.9 4.7 4.6 5.  5.4 4.6 5.  4.4 4.9 5.4 4.8 4.8 4.3 5.8 5.7 5.4 5.1
  5.7 5.1 5.4 5.1 4.6 5.1 4.8 5.  5.  5.2 5.2 4.7 4.8 5.4 5.2 5.5 4.9 5.
  5.5 4.9 4.4 5.1 5.  4.5 4.4 5.  5.1 4.8 5.1 4.6 5.3 5.  7.  6.4 6.9 5.5
  6.5 5.7 6.3 4.9 6.6 5.2 5.  5.9 6.  6.1 5.6 6.7 5.6 5.8 6.2 5.6 5.9 6.1
  6.3 6.1 6.4 6.6 6.8 6.7 6.  5.7 5.5 5.5 5.8 6.  5.4 6.  6.7 6.3 5.6 5.5
  5.5 6.1 5.8 5.  5.6 5.7 5.7 6.2 5.1 5.7 6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3
  6.7 7.2 6.5 6.4 6.8 5.7 5.8 6.4 6.5 7.7 7.7 6.  6.9 5.6 7.7 6.3 6.7 7.2
  6.2 6.1 6.4 7.2 7.4 7.9 6.4 6.3 6.1 7.7 6.3 6.4 6.  6.9 6.7 6.9 5.8 6.8
  6.7 6.7 6.3 6.5 6.2 5.9]
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5
  3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.  3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2
  3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3
  2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8
  2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5
  2.6 3.  2.

In [79]:
iris_cp = iris.copy()
iris_cp

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [86]:
X = np.random.rand(4,4)

In [88]:
#matrix product
X_sq =X.T.dot(X)
print(X_sq)

[[1.25956667 1.08179529 0.66945183 1.01441545]
 [1.08179529 1.62729477 1.11273297 1.46514121]
 [0.66945183 1.11273297 1.40578818 1.48458255]
 [1.01441545 1.46514121 1.48458255 1.69673147]]


In [89]:
#Matrix Inverse
X_sq_inv = ln.inv(X_sq)
print(X_sq_inv)

[[  2637.88641532   3915.55025236  11588.34769178 -15097.61915162]
 [  3915.55025236   5822.67964695  17218.01315626 -22434.07700381]
 [ 11588.34769178  17218.01315626  50944.13153625 -66370.5425784 ]
 [-15097.61915162 -22434.07700381 -66370.5425784   86470.90054906]]


In [90]:
#SVD decomposition of iris_cp
iris_svd = ln.svd(iris_cp)
print(iris_svd[1])

[95.95991387 17.76103366  3.46093093  1.88482631]


In [91]:
#Left-Singular vectors
print(iris_svd[0])

[[-0.06161685  0.12961144  0.0021386  ... -0.09343429 -0.09573864
  -0.08085465]
 [-0.05807094  0.11101978  0.07067239 ...  0.03690405 -0.03153954
   0.01309526]
 [-0.05676305  0.11796647  0.00434255 ...  0.03066199  0.19531473
   0.13569909]
 ...
 [-0.0940593  -0.0498297  -0.04144001 ...  0.98181631 -0.02194514
  -0.00894446]
 [-0.09488961 -0.05610123 -0.21297821 ... -0.02155617  0.94178018
  -0.02971961]
 [-0.08847836 -0.0515697  -0.09575285 ... -0.0086052  -0.03021088
   0.9736599 ]]


In [92]:
print(iris_svd[0].shape)

(150, 150)


In [93]:
#Right-simulator vector
print(iris_svd[2])

[[-0.75110816 -0.38008617 -0.51300886 -0.16790754]
 [ 0.2841749   0.5467445  -0.70866455 -0.34367081]
 [ 0.50215472 -0.67524332 -0.05916621 -0.53701625]
 [ 0.32081425 -0.31725607 -0.48074507  0.75187165]]


In [94]:
print(iris_svd[2].shape)

(4, 4)


## Employing array methods and functions

In [95]:
import numpy as np 
from numpy.random import randn

arr1 = np.array(randn(4,4)*10,dtype = np.int8)
print(arr1)

[[ -1  -5   8   7]
 [  1  13   4 -12]
 [ -1 -11   0  11]
 [  0  -1  -8  21]]


In [96]:
arr1.tolist()

[[-1, -5, 8, 7], [1, 13, 4, -12], [-1, -11, 0, 11], [0, -1, -8, 21]]

In [97]:
arr1.flatten()

array([ -1,  -5,   8,   7,   1,  13,   4, -12,  -1, -11,   0,  11,   0,
        -1,  -8,  21], dtype=int8)

In [99]:
arr2 = np.empty((4,3),dtype=np.dtype('<U16'))
arr2.fill("Carlos")
arr2

array([['Carlos', 'Carlos', 'Carlos'],
       ['Carlos', 'Carlos', 'Carlos'],
       ['Carlos', 'Carlos', 'Carlos'],
       ['Carlos', 'Carlos', 'Carlos']], dtype='<U16')

In [100]:
arr1.sum()

26

In [102]:
arr1.sum(axis=1)

array([ 9,  6, -1, 12])

In [103]:
#cumulative sums
arr1.cumsum(axis=0)

array([[-1, -5,  8,  7],
       [ 0,  8, 12, -5],
       [-1, -3, 12,  6],
       [-1, -4,  4, 27]])

In [104]:
#Vectorization with ufuncs
np.sign(arr1)

array([[-1, -1,  1,  1],
       [ 1,  1,  1, -1],
       [-1, -1,  0,  1],
       [ 0, -1, -1,  1]], dtype=int8)

In [106]:
arr1 =np.sign(arr1)
arr1

array([[-1, -1,  1,  1],
       [ 1,  1,  1, -1],
       [-1, -1,  0,  1],
       [ 0, -1, -1,  1]], dtype=int8)

In [107]:
#square root
np.sqrt(arr1 * np.sign(arr1))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 0., 1.],
       [0., 1., 1., 1.]], dtype=float16)

In [108]:
def tr(a):
    if (a>0):
        return a
    else:
        return 0

#testing tr()
tr(20)

20

In [109]:
tr(-20)

0

In [110]:
print(arr1>0)

[[False False  True  True]
 [ True  True  True False]
 [False False False  True]
 [False False False  True]]


In [111]:
tr(arr1)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [112]:
tr_vec =np.vectorize(tr)
tr_vec(arr1)

array([[0, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]])

In [113]:
def tr_vec_fast(arr):
    ret_arr = arr.copy()
    ret_arr[arr<=0]=0
    return ret_arr

tr_vec_fast(arr1)

array([[0, 0, 1, 1],
       [1, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 1]], dtype=int8)

In [114]:
%timeit tr_vec(arr1)

21.4 µs ± 548 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [115]:
%timeit tr_vec_fast(arr1)

3.43 µs ± 44.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
